# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-db-todolist
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/db:/var/lib/mysql
volumes:
  db:
    driver: local